name: "mintest"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - run: nix-build
    - run: nix-shell --run "echo OK"
    - run: nix-instantiate --eval -E '(import <nixpkgs-unstable> {}).lib.version'


